autoware_system_design_format: v0.1.0

name: vehicle_x.deployment

system: TypeAlpha.system

variables:
  - name: vehicle_id
    value: vehicle_x
  - name: data_path
    value: $(env HOME)/autoware_data
  - name: lanelet2_map_file
    value: lanelet2_map.osm
  - name: pointcloud_map_file
    value: pointcloud_map.pcd
